name: Greetings

on:
  push:
    branches:
      - master # Specify the branch you want to trigger the action on (e.g., 'main')
  pull_request:
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GREETINGS_TOKEN }}
        issue-message: "Thanks for raising this issue. I will look at it as soon as possible"
        pr-message: "Thanks for raising this pr. I will take a look and merge it asap"
